version: "3"
services:
  test-backend-volto-searchkit-block:
    image: plone/plone-backend:5.2.8
    environment:
      ZSERVER_HOST: "0.0.0.0"
      ZSERVER_PORT: "55001"
      APPLY_PROFILES: "plone.app.contenttypes:plone-content,plone.restapi:default,plone.volto:default-homepage"
      ADDONS: "plone.app.robotframework==2.0.0a6 plone.app.testing==7.0.0a3 plone.app.contenttypes plone.restapi plone.volto"
      CONFIGURE_PACKAGES: "plone.app.contenttypes,plone.restapi,plone.volto,plone.volto.cors"
      DEVELOP: "git+https://github.com/collective/collective.elastic.plone@master#egg=collective.elastic.plone git+https://github.com/collective/collective.elastic.ingest.git"
      SITE: "plone"
    ports:
      - "55001:55001"
    command: ./bin/robot-server plone.app.robotframework.testing.VOLTO_ROBOT_TESTING
    volumes:
      - ./src/:/app/src/
      # - ./var:/app/var
