version: "3"

services:
  addon-acceptance:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION:-16}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
    ports:
      - 3000:3000
    depends_on:
      - backend-acceptance
    profiles:
      - prod

  backend-acceptance:
    image: plone/plone-backend:${PLONE_VERSION:-6}
    command: ./bin/robot-server plone.app.robotframework.testing.VOLTO_ROBOT_TESTING
    # command: bin/celery -A collective.elastic.ingest.celery.app multi restart workersearchkitblock --logfile="/app/celery/celery%n%I.log" --pidfile="/app/celery/celery%n.pid" > /dev/null 2>&1 &; bin/robot-server plone.app.robotframework.testing.VOLTO_ROBOT_TESTING > /dev/null 2>&1 &;
    volumes:
      - ./configuration/ploneconfiguration/:/app/ploneconfiguration/
    environment:
      # ##### plone.app.robotframework
      ZSERVER_HOST: "0.0.0.0"
      ZSERVER_PORT: "55001"
      APPLY_PROFILES: "plone.app.contenttypes:plone-content,plone.restapi:default,plone.volto:default-homepage, rohberg.elasticsearchblocks:testing"
      CONFIGURE_PACKAGES: "plone.app.contenttypes,plone.restapi,plone.volto,plone.volto.cors,rohberg.elasticsearchblocks"
      # INSTALL_PRODUCTS: "collective.elastic.plone,collective.elastic.ingest,rohberg.elasticsearchblocks"
      # ##### plone-backend docker image
      ADDONS: "plone.app.robotframework==2.0.0a6 plone.app.testing==7.0.0a3 plone.app.contenttypes plone.restapi plone.volto celery redis collective.elastic.plone collective.elastic.ingest rohberg.elasticsearchblocks"
      SITE: "plone"
      # DEVELOP: "git+https://github.com/collective/collective.elastic.plone.git#egg=collective.elastic.plone"

      CELERY_BROKER: redis://host.docker.internal:6379
      ELASTICSEARCH_INDEX: plone
      ELASTICSEARCH_QUERY_SERVER: http://host.docker.internal:9200
      ELASTICSEARCH_QUERY_USE_SSL: 0

      # CELERY_BROKER: redis://localhost:6379/0
      ELASTICSEARCH_INGEST_SERVER: host.docker.internal:9200
      ELASTICSEARCH_INGEST_USE_SSL: 0

      PLONE_SERVICE: http://127.0.0.1:55001
      PLONE_PATH: Plone
      PLONE_USER: admin
      PLONE_PASSWORD: secret

      ANALYSIS_FILE: /app/ploneconfiguration/elasticsearch-analysis.json
      MAPPINGS_FILE: /app/ploneconfiguration/elasticsearch-mappings.json
      PREPROCESSINGS_FILE: /app/ploneconfiguration/elasticsearch-preprocessings.json
    ports:
      - 55001:55001
    profiles:
      - dev
      - prod
    depends_on:
      - redis
      - elk
  elk:
    image: ksuess/rohberg-elk:rc5
    # image: sebp/elk:oss-8.1.0
    environment:
      # ES_CORS_ALLOW_ORIGIN: "/https?://(.*)localhost(.*)/"
      ES_CORS_ALLOW_ORIGIN: "*"
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ./configuration/elasticsearchconfiguration/elasticsearch-keywords.txt:/etc/elasticsearch/elasticsearch-keywords.txt
      - ./configuration/elasticsearchconfiguration/elasticsearch-lexicon.txt:/etc/elasticsearch/elasticsearch-lexicon.txt
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
