name: Code analysis checks
on: [push]
jobs:
  codeanalysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.10]

    steps:
      - name: Main checkout
        uses: actions/checkout@v3

      - name: Linting
        run: make lint
